### ISSUE TITLE
Combining with webcam shows no image output on nicegui page

### ISSUE THREAD

**Issue by thetabs** [JensOgorek/image_displaying_example#1]
I tried the example in this with the modification that I didn't use the image_sender node to send my images, instead, I used a single webcam with the usb_cam ROS2 node (also a realsense with realsense_ros2 node) to send my images on the topic `/camera/color/image_raw`. I try to cache them in the image_callback and display this image on [`self.sub_image`](https://github.com/JensOgorek/image_displaying_example/blob/main/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47). However I face two issues:
- `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 9: invalid continuation byte` I found that changing the decoding type in [this line](https://github.com/JensOgorek/image_displaying_example/blob/main/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L65) from `utf-8` to `latin-1` let's me go further
- Now there is no error output and the webgui shows nothing, only a blank white page

What are possible causes?
- The decoding type is wrong, in which case please help me with what it should be, whether `utf-8` or `latin-1, `utf-8` does not seem to work on my machine
- The image is probably not being subscribed, which is not the case as I can print the data from the message
- The image is coming in at a very high frequency, here I throttled the message in the callback to 1fps, which in my opinion should be low enough, but I even tried at 0.1fps, and still no image was seen
- Usually in streamlit, I found that the web page would pop up asking for permission to access the camera. However, this time with nicegui it did not. Do I have to set camera permissions? If so how do I do that?

Please help, thanks in advance, and thanks for the good work.

**Comment by JensOgorek** [comment]
I tried to see if I can replicate the problem.

- I used ROS2 usb_cam [(Link)](https://index.ros.org/p/usb_cam/) with default settings and the default usb cam.
- I validated that I have an image with rviz2
- changed the [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L18) to the default topic "image_raw":
```python3
self.subscription1 = self.create_subscription(Image, 'image_raw', self.image_callback1, 10)
```
Besides not having a buffer and the cam sending the images very fast, everything worked

This is my output (after shutting down usb_cam, so I don't get new frames).
![img_test](https://github.com/JensOgorek/image_displaying_example/assets/134612744/bb28f02c-4aed-4760-a2c2-a8418f35e3b4)

**Comment by JensOgorek** [comment]
My best guess would be the encoding. If the image gets decoded correctly, you should be able to use any base64 image viewer. 
If not, you have to find out what the correct encoding is for your case. 
Also, changing the output settings of the webcam might help (you can write a config-file for the usb_cam node).
Just for testing, you could also use a different cam, if you have one.

**Comment by JensOgorek** [comment]
I continued to test myself. I found another webcam, that worked. Also, I tried to change some settings to force the camera to fail, it did not fail. Even when RViz failed, I got an image with my node.
When you use usb_node you can just ```ros2 param dump /usb_cam --output-dir <directory>``` and use this as config for your node ```ros2 run usb_cam usb_cam_node_exe --ros-args --params-file /path/to/your/yaml/usb_cam.yaml```

**Comment by thetabs** [comment]
Thanks for the reply and also for testing things yourself!

It seemed I had a corrupted installation of the base64 python package, I don't know how that happened lol! But I reinstalled base64 and with utf-8, the right encoding happens. How did I check this? through manually printing the encoded base64 string  that was output from `encoded_image_to_base64()` and using this base64 to image decoder https://base64.guru/converter/decode/image. to see the encoded image which turns out to be correct.

I even tried with different browsers (firefox, chrome, chromium, edge), and while the example in this repository works (displaying image with character 1 or 2), the camera topic does not work, it still shows a blank screen, but it seems like the image tile is refreshing everytime a new image is received. A gif of this is attached.
![Screencast from 29-08-23 12 56 10](https://github.com/JensOgorek/image_displaying_example/assets/135217456/4191c72e-f749-4e53-a6e3-d60596c4a87b)

However, RViz shows the correct image




> I continued to test myself. I found another webcam, that worked. Also, I tried to change some settings to force the camera to fail, it did not fail. Even when RViz failed, I got an image with my node. When you use usb_node you can just `ros2 param dump /usb_cam --output-dir <directory>` and use this as config for your node `ros2 run usb_cam usb_cam_node_exe --ros-args --params-file /path/to/your/yaml/usb_cam.yaml`

I think the configuration I have is correct, I also tried with other parameters, through `ros2 param set` and also with the config.yaml, but I don't think the configurations are a problem.

What else could be the problem?

**Comment by JensOgorek** [comment]
> It seemed I had a corrupted installation of the base64 python package, I don't know how that happened lol! But I reinstalled base64 and with utf-8, the right encoding happens. How did I check this? through manually printing the encoded base64 string that was output from encoded_image_to_base64() and using this base64 to image decoder https://base64.guru/converter/decode/image. to see the encoded image which turns out to be correct.

That's the way I would have tested it as well.

> I even tried with different browsers (firefox, chrome, chromium, edge), and while the example in this repository works (displaying image with character 1 or 2), the camera topic does not work, it still shows a blank screen, but it seems like the image tile is refreshing everytime a new image is received. A gif of this is attached.

I've not seen this one yet. How fast is the frame rate of the camera? The screenshot I added was after I stopped the node, so NiceGui only shows the last image it received.

> What else could be the problem?

If the image does not show up, even on a low frame rate, I would save the base64 string and write a very simple Nicegui program without ROS and anything. Just like the image [example ](https://nicegui.io/documentation/image#base64_string). If it still fails but works with other base64 viewers, we might have the source of the evil.

As a Hail Mary, you could also replace the ui.image with an [ui.interactive_image](https://nicegui.io/documentation/interactive_image)

**Comment by thetabs** [comment]
> I've not seen this one yet. How fast is the frame rate of the camera? 

I tested it for [10, 5, 2, 1, 0.5, 0.1, 0.05] fps

> If the image does not show up, even on a low frame rate, I would save the base64 string and write a very simple Nicegui program without ROS and anything. Just like the image [example ](https://nicegui.io/documentation/image#base64_string). If it still fails but works with other base64 viewers, we might have the source of the evil.

I think this is indeed the source of evil. I printed the base64 string of a frame from the camera topic and ran the image example with my own base64 string, and the image does indeed show up in the browser.
![image](https://github.com/JensOgorek/image_displaying_example/assets/135217456/fd6860af-84e7-4e41-902e-19db5b52a6da)

The example I wrote is as follows
```python
from nicegui import ui

base64 = 'data:image/png;base64,<THE_LONGEST_STRING_I_HAVE_EVER_COPIED>'

ui.image(base64)
ui.run()
```  
Additionally I found that github allows only 65536 characters in the comment box :wink: 

Why is the result different now? Are base64 strings being handled differently in the ros node?

> As a Hail Mary, you could also replace the ui.image with an [ui.interactive_image](https://nicegui.io/documentation/interactive_image)

Changing to ui.interactive_image gives me this 
![image](https://github.com/JensOgorek/image_displaying_example/assets/135217456/7f9cc416-6a7c-4a37-9192-f6decdda8d1e)

**Comment by JensOgorek** [comment]
> I think this is indeed the source of evil. I printed the base64 string of a frame from the camera topic and ran the image example with my own base64 string, and the image does indeed show up in the browser.

So, you basically printed base64_image or saved it to a file from this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L45)?

**Comment by thetabs** [comment]
> > I think this is indeed the source of evil. I printed the base64 string of a frame from the camera topic and ran the image example with my own base64 string, and the image does indeed show up in the browser.
> 
> So, you basically printed base64_image or saved it to a file from this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L45)?

I printed it, did not save a file

**Comment by JensOgorek** [comment]
That is so weird, and if you add the base64 string by hand to this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47), it works as well?

**Comment by thetabs** [comment]
> That is so weird, and if you add the base64 string by hand to this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47), it works as well?

Interestingly, no. This is what I get. I also tried to add it to the other set_source line in image_callback2(), the result is the same.
![image](https://github.com/JensOgorek/image_displaying_example/assets/135217456/f91cfec3-b7e5-4ecf-b678-64d4b5215cd6)

The only difference in the above comment where the image was displayed and this one is the set_source(). But I think set_source is the only way you can get a refreshable image tile, right?

**Comment by JensOgorek** [comment]
Yeah, maybe you have to create an Issue within the NiceGUI git for that. That sounds like a bug to me

**Comment by thetabs** [comment]
can i link this issue there?

**Comment by JensOgorek** [comment]
First, can you give me the string and I test it myself?

**Comment by thetabs** [comment]
here you go 
https://drive.google.com/file/d/1e-Q6xspwgGa8ZJ_WRYh6mTYjsaMvRYRw/view?usp=sharing

**Comment by JensOgorek** [comment]
That is indeed a big string. The issue might be with the length of the string itself, coming over the .set_source function. I think opening an issue with NiceGUI might be a good step now.
To avoid this problem, you might want to lower your resolution and see if the string gets shorter or use a different technique by temporary saving the received file and loading it directly (again with set_source, but coming from a local file).

**Comment by thetabs** [comment]
> The issue might be with the length of the string itself, coming over the .set_source function

I don't think that is the case, because I tried the simple image example like this
```python
from nicegui import ui

base64 = 'data:image/png:base64,<STRING>'

img = ui.image()
img.set_source(base64)
ui.run()
``` 

and it is able to display the image.

But I shall consider the option of saving the image temporarily and displaying it.

**Comment by JensOgorek** [comment]
I just tested it with my code. It ran, but only half the image. Important: You have to trigger the callback to load it, if you add it on line 59 or 47.

**Comment by thetabs** [comment]
> I just tested it with my code. It ran, but only half the image. Important: You have to trigger the callback to load it, if you add it on line 59 or 47.

What does this mean? Do you mean to add the string to both the image callbacks? Then I've tried that already as explained in this comment.


> > That is so weird, and if you add the base64 string by hand to this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47), it works as well?
> 
> Interestingly, no. This is what I get. I also tried to add it to the other set_source line in image_callback2(), the result is the same. ![image](https://user-images.githubusercontent.com/135217456/264017499-f91cfec3-b7e5-4ecf-b678-64d4b5215cd6.png)
> 
> The only difference in the above comment where the image was displayed and this one is the set_source(). But I think set_source is the only way you can get a refreshable image tile, right?

**Comment by JensOgorek** [comment]
> > I just tested it with my code. It ran, but only half the image. Important: You have to trigger the callback to load it, if you add it on line 59 or 47.
> 
> What does this mean? Do you mean to add the string to both the image callbacks? Then I've tried that already as explained in this comment.
> 
> > > That is so weird, and if you add the base64 string by hand to this [line](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47), it works as well?
> > 
> > 
> > Interestingly, no. This is what I get. I also tried to add it to the other set_source line in image_callback2(), the result is the same. ![image](https://user-images.githubusercontent.com/135217456/264017499-f91cfec3-b7e5-4ecf-b678-64d4b5215cd6.png)
> > The only difference in the above comment where the image was displayed and this one is the set_source(). But I think set_source is the only way you can get a refreshable image tile, right?

Yeah, but did you trigger the callbacks?

**Comment by thetabs** [comment]
Ah right, the callbacks weren't triggered, I can now see the duck 
![image](https://github.com/JensOgorek/image_displaying_example/assets/135217456/da084004-2585-418f-99c4-b618b73c2dbc)

But how does this tie back to the previous question? Would I have to read the string differently?

**Comment by JensOgorek** [comment]
My best guess is, that it has to do with the amount of characters and being read differently from a variable or directly. Do you still use latin-1 or utf-8?
In your case, I would save it locally and see if this works. You can still create an Issue. We could also think about adding the ability to display cv2.images directly. You might want to add that to the issue.

**Comment by thetabs** [comment]
Ok I got a brainwave with my last statement and apparently, it works. I modified [line 47](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47) as an [f string](https://peps.python.org/pep-0498/) and the base64 string is read correctly. So that solves the problem I've been facing. 

Thanks so much for being patient with me. You deserve a cookie :cookie: and beers :beers:. 

I have some additional remarks/points of improvement. The overall code in your repository would stay the same for your example, except [line 47](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47) and [line 58](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L58C9-L58C9) would need f-strings instead of traditional string appending.

I know it is out of scope for the purpose of this repository, but in case you need a camera streaming example with ros2 (like with the opencv-webcam example). It is good to know that with ui.image() in [this line ](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L30), you get sort of a stuttered video like so
![ezgif com-video-to-gif](https://github.com/JensOgorek/image_displaying_example/assets/135217456/4ac8a1ee-ad9f-488a-8638-57e9f541d8e7)


But if you replace it with ui.interactive_image() instead, then the streaming is so much smoother and a lot faster (this gif is at 10fps)
![ezgif com-video-to-gif](https://github.com/JensOgorek/image_displaying_example/assets/135217456/0d87259a-c095-46fd-b63e-97a7befd3590)


Here is the code snippet for the streaming in a ros2 node example, that I modified from your code
```python
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

from nicegui import app, globals, run, ui
import threading
from pathlib import Path
from rclpy.executors import ExternalShutdownException
import base64
import time

class ImageReceiverNode(Node):
    def __init__(self) -> None:
        super().__init__('image_receiver_node')
        #create two subscriptions for the two images
        self.subscription1 = self.create_subscription(Image, '/camera/color/image_raw', self.image_callback1, 10)
        #adding CV bridge for image processing
        self.cv_bridge = CvBridge()
        #this is for switching between the two images
        self.show_img1 = True

        self.throttle_msg = 1 / 10 # [s]
        self.last_update_time = 0.0

        #this is where we add nicegui elements
        with globals.index_client:
            #create a row with a width of 40%
            with ui.row().style('width: 40%;'):
                #create an empty image element
                self.sub_image = ui.interactive_image()

    def image_callback1(self, msg) -> None:
        #check if the first image should be shown
        current_time = time.time()
        if current_time - self.last_update_time >= self.throttle_msg:
            self.last_update_time = current_time
            #convert the image to a cv::Mat
            image = self.cv_bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
            #encode the image to base64
            base64_image = self.encode_image_to_base64(image)
            #set the image source to the base64 string to display it
            self.sub_image.set_source(f'data:image/png;base64,{base64_image}')
        return
    
    def encode_image_to_base64(self, image) -> None:
        # Convert image to binary format
        _, image_data = cv2.imencode('.png', image)  
        # encode the binary image to base64
        base64_image = base64.b64encode(image_data).decode('utf-8')
        #return the base64 string
        return base64_image

def ros_main() -> None:
    #Standart ROS2 node initialization
    print('Starting ROS2...', flush=True)

    rclpy.init()
    image_receiver = ImageReceiverNode()

    try:
        rclpy.spin(image_receiver)
    except ExternalShutdownException:
        pass

def main():
    pass # NOTE: This is originally used as the ROS entry point, but we give the control of the node to NiceGUI.

#Starting the ros node in a thread managed by nicegui. It will restarted with "on_startup" after a reload.
#It has to be in a thread, since NiceGUI wants the main thread for itself.
app.on_startup(lambda: threading.Thread(target=ros_main).start())

#This is for the automatic reloading by nicegui/fastapi
run.APP_IMPORT_STRING = f'{__name__}:app'

#We add reload dirs to just watch changes in our package
ui.run(title='Img show with NiceGUI',uvicorn_reload_dirs=str(Path(__file__).parent.resolve()))

``` 

What I also observed was that throttling the image message to less than half of the camera stream rate is necessary as if you have a low throttle time (higher fps), then the output in the webgui increasingly lags as time progresses. This could be a buffering issue on the nicegui side as RViz works well at near-source frame rates. But for my application, this is good enough. Something to consider for the future, I could open an issue in the nicegui git for this.

Finally, thank you so much @JensOgorek, for all the help. Hopefully, I can now make a nice GUI :wink:. I will close the issue as it has been solved.

**Comment by JensOgorek** [comment]
That's amazing. Glad it worked out in the end.

> I have some additional remarks/points of improvement. The overall code in your repository would stay the same for your example, except [line 47](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L47) and [line 58](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L58C9-L58C9) would need f-strings instead of traditional string appending.

I'll check that out and might add it to the example, maybe other people will have this problem as well. Nice Find.

>I know it is out of scope for the purpose of this repository, but in case you need a camera streaming example with ros2 (like with the opencv-webcam example). It is good to know that with ui.image() in [this line ](https://github.com/JensOgorek/image_displaying_example/blob/ed41ca978269aab0fcb7a75443efe23c5ef88dcc/nicegui_image_receiver/nicegui_image_receiver/receiver.py#L30), you get sort of a stuttered video like so

That is indeed interesting. Most likely since ui.image() is made for static images, I think. I checked another [example ](https://github.com/zauberzeug/nicegui/blob/833b0cc9fc5fd8facee5c682e2c4816066de2958/examples/opencv_webcam/main.py#L45) with OpenCV, and we use interactive_iamge there as well.

I'll add these changes tomorrow, and happy coding.

Edit: Also in the same [example](https://github.com/zauberzeug/nicegui/blob/833b0cc9fc5fd8facee5c682e2c4816066de2958/examples/opencv_webcam/main.py#L49), you can find f string as well :D
